[functions]
    directory = "functions/"
    
[[redirects]]
    from = "/*"
    to = "index.html"
    status = 200
  
[dev]
    targetPort = 8000

[context.production]
    NODE_ENV = "production"

[context.dev.environment]
    NODE_ENV = "development"